name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Setup environment
        run: |
          cp .env.example .env


      - name: Starting DB Docker
        run: |
          pwd
          ls -la
          chmod +x market_agents/agents/db/run_setup.sh
          chmod +x market_agents/agents/db/setup_pgvector.sh
          docker compose -f ./market_agents/agents/db/docker-compose.yaml up --build -d
          # Wait for containers to be ready
          sleep 10
          docker compose -f ./market_agents/agents/db/docker-compose.yaml ps
          docker compose -f ./market_agents/agents/db/docker-compose.yaml exec -T app /market_agents/agents/db/setup_pgvector.sh      
      - name: Run tests
        run: |
          # Replace with your test command


